# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xa7a75tfgg484-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/project_2/project_2.srcs/sources_1/new/clock_divider.v
  C:/project_2/project_2.srcs/sources_1/new/led_driver.v
  C:/project_2/project_2.srcs/sources_1/new/time_counter.v
  C:/project_2/project_2.srcs/sources_1/new/MyClockTop.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/project_2/project_2.srcs/constrs_1/new/watch_top.xdc
set_property used_in_implementation false [get_files C:/project_2/project_2.srcs/constrs_1/new/watch_top.xdc]


synth_design -top MyClockTop_LED -part xa7a75tfgg484-1I


write_checkpoint -force -noxdef MyClockTop_LED.dcp

catch { report_utilization -file MyClockTop_LED_utilization_synth.rpt -pb MyClockTop_LED_utilization_synth.pb }
