set_property PACKAGE_PIN F14 [get_ports {led[2]}]
set_property PACKAGE_PIN F13 [get_ports {led[1]}]
set_property PACKAGE_PIN F15 [get_ports {led[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {digit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports push1]
set_property IOSTANDARD LVCMOS33 [get_ports push2]
set_property IOSTANDARD LVCMOS33 [get_ports push3]
set_property IOSTANDARD LVCMOS33 [get_ports push4]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN F16 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN D14 [get_ports {digit[3]}]

set_property PACKAGE_PIN D16 [get_ports {digit[2]}]
set_property PACKAGE_PIN E14 [get_ports {digit[0]}]


set_property PACKAGE_PIN E16 [get_ports {digit[1]}]


set_property PACKAGE_PIN AB11 [get_ports {digit[4]}]
set_property PACKAGE_PIN AB12 [get_ports {digit[5]}]
set_property PACKAGE_PIN D20 [get_ports {seg[0]}]
set_property PACKAGE_PIN C20 [get_ports {seg[1]}]
set_property PACKAGE_PIN C22 [get_ports {seg[2]}]
set_property PACKAGE_PIN B22 [get_ports {seg[3]}]
set_property PACKAGE_PIN B21 [get_ports {seg[4]}]
set_property PACKAGE_PIN A21 [get_ports {seg[5]}]
set_property PACKAGE_PIN E22 [get_ports {seg[6]}]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN U7 [get_ports reset]
set_property PACKAGE_PIN E21 [get_ports push1]
set_property PACKAGE_PIN D21 [get_ports push2]
set_property PACKAGE_PIN G22 [get_ports push3]
set_property PACKAGE_PIN F21 [get_ports push4]
